name: ia_nano
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - ase
  - rdkit
  - nglview
  - py3Dmol
  - openmm
  - mendeleev
  - pip
